{
 "title": "FlyByWire Simulations",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Live Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  lastContact AS \"time\",\r\n  trueAltitude AS \"Altitude\",\r\n  ST_Y(location) AS \"latitude\",\r\n  ST_X(location) AS \"longitude\",\r\n  flight\r\nFROM telex_connection\r\nWHERE\r\n  isActive = '1'\r\nORDER BY firstContact"
    }
   ]
  },
  {
   "title": "Active flights",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*),\r\n  $__timeTo() AS \"time\"\r\nFROM telex_connection\r\nWHERE\r\n  $__timeFilter(lastContact)\r\nAND\r\n  isActive = '1'\r\nORDER BY lastContact"
    }
   ]
  },
  {
   "title": "Flights last week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(firstContact,$__interval),\r\n  count(*) AS \"Count\"\r\nFROM telex_connection\r\nWHERE\r\n  $__timeFilter(firstContact)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(firstContact,$__interval)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/flybywiresim/fbw-branding/master/svg/FBW-Logo.svg\"/>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  firstContact AS \"time\",\n  trueAltitude\nFROM telex_connection\nWHERE\n  $__timeFilter(firstContact)\nORDER BY firstContact"
    }
   ]
  },
  {
   "title": "Active Flights",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  flight AS \"Flight\",\r\n  trueAltitude AS \"Altitude\",\r\n  heading AS \"Heading\",\r\n  freetextEnabled AS \"TELEX enabled\",\r\n  aircraftType AS \"AC Type\",\r\n  DATE_FORMAT(firstContact, '%H:%iZ') AS \"First Contact\"\r\nFROM telex_connection\r\nWHERE\r\n  isActive = '1'\r\nORDER BY flight"
    }
   ]
  }
 ]
}