{
 "title": "Telex Messages",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*) AS \"Count\"\r\nFROM telex_message\r\nWHERE\r\n  $__timeFilter(createdAt)"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*) AS \"Count\"\r\nFROM telex_message\r\nWHERE\r\n  $__timeFilter(createdAt)\r\nAND\r\n  received = 1"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "table",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  telex_message.createdAt AS \"Time\",\n  c1.flight AS \"Sender\",\n  c2.flight AS \"Recipient\",\n  telex_message.isProfane AS \"Profane\",\n  REPLACE(telex_message.message, ';', ' ') AS \"Message\"\nFROM telex_message\nLEFT OUTER JOIN telex_connection c1 ON telex_message.fromId = c1.id\nLEFT OUTER JOIN telex_connection c2 ON telex_message.toId = c2.id\nWHERE\n  $__timeFilter(createdAt)\nORDER BY createdAt"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(createdAt,$__interval),\r\n  count(*) AS \"Count\"\r\nFROM telex_message\r\nWHERE\r\n  $__timeFilter(createdAt)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(createdAt,$__interval)"
    }
   ]
  }
 ]
}