image:
  repository: flybywiresim/api
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  port: 3000

ingress:
  fqdn: ~
  tls:
    enabled: false
    issuer: ~

api:
  logger:
    level: info
    format: json
  database:
    host: ~
    port: 3306
    database: fbw
    user: fbw
    password: somePassword
    logging: error
    connectionLimit: 5
  redis:
    host: ~
    port: 6379
  telex:
    timeoutMin: 6
  auth:
    secret: someSecret
    expires: 12h
