export const BannedFlightNumbers = [
    'DISPATCH',
    'DISPATCHER',
    'FBW',
    'FBWTEAM',
    'FLYBYWIRE',
    'SYSTEM',
    'MSFS',
    'ATC',
    'GROUND',
    'VATSIM',
    'IVAO',
    'PILOTEDGE',
    'PILOT EDGE',
    'POSCON',
    'AAL11',
    'AA11',
    'UAL93',
    'UA93',
    'AAL77',
    'AA77',
    'MAS17',
    'MH17',
    'MAS370',
    'MH370',
    'UAL175',
    'UA175',
    'AF447',
    'MSR990',
    'MSR804',
    'SJ182',
    'SJY182',
];

export const BlockedMessageFilters = [
    // Frequent spam
    'LDS.ORG',
    'LDSORG',
    'COMEUNTOCHRIST',
    'COME UNTO CHRIST',
    'BOOKOFMORMON',
    'BOOK OF MORMON',
    'CHURCHOFJESUSCHRIST',
    'JESUS',
    'CHRIST',
    'CHURCH',
    'ALLAH',
    'GOD',
    // Common TLD's
    '.COM',
    '.ORG',
    '.NET',
    '.IO',
    '. COM',
    '. ORG',
    '. NET',
    '. IO',
    // Tiny URLs
    'RB.GY',
    'CUTT.LY',
    'BIT.LY',
];
