ingress:
  fqdn: api.staging.flybywiresim.com
  tls:
    enabled: true
    issuer: letsencrypt-staging

api:
  database:
    host: mysql-flybywire-api-do-user-8167919-0.b.db.ondigitalocean.com
    port: 25060
  redis:
    host: redis-staging-master.redis-staging.svc.cluster.local
  telex:
    timeoutMin: 15
