apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
data:
  databasePassword: {{ .Values.api.database.password | b64enc }}
  authSecret: {{ .Values.api.auth.secret | b64enc }}
