name: Staging CI

on:
  push:
    branches: staging

jobs:
  lint_helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./charts/fbw-api
  build_and_push:
    runs-on: ubuntu-latest
    env:
      SHA7: ${GITHUB_SHA::7}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: flybywiresim/api:staging,flybywiresim/api:$SHA7
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  depoly_staging:
    runs-on: ubuntu-latest
    needs: [build_and_push, lint_helm]
    env:
      SHA7: ${GITHUB_SHA::7}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --set api.database.password=${{ secrets.STAGING_DB_PASSWORD }},api.auth.secret=${{ secrets.STAGING_AUTH_SECRET }},image.tag=$SHA7 -f ./charts/fbw-api/values.yaml -f ./charts/fbw-api/environments/staging.yaml fbw-api-staging ./charts/fbw-api
